type: Item
folder: null
name: Values
color: null
sorting: a
_id: 7wnAzgh72y7x7ftp
description: ''
sort: 0
flags: {}
_stats:
  compendiumSource: null
  duplicateSource: null
  exportSource: null
  coreVersion: '13.351'
  systemId: sta
  systemVersion: 2.4.5
  createdTime: 1765451329883
  modifiedTime: 1765451329883
  lastModifiedBy: h6PQP2LANMyAy0DY
_key: '!folders!7wnAzgh72y7x7ftp'
