type: Item
folder: null
name: Values
color: null
sorting: a
_id: ZJr0gR5cWuowPaJB
description: ''
sort: 0
flags: {}
_stats:
  compendiumSource: null
  duplicateSource: null
  exportSource: null
  coreVersion: '13.351'
  systemId: sta
  systemVersion: 2.4.5
  createdTime: 1765450929162
  modifiedTime: 1765450929162
  lastModifiedBy: h6PQP2LANMyAy0DY
_key: '!folders!ZJr0gR5cWuowPaJB'
