type: JournalEntry
folder: null
name: Environment
color: null
sorting: a
_id: Kjpd5UzKteKgjIqB
description: ''
sort: 0
flags: {}
_stats:
  compendiumSource: null
  duplicateSource: null
  exportSource: null
  coreVersion: '13.351'
  systemId: sta
  systemVersion: 2.4.5
  createdTime: 1765451995523
  modifiedTime: 1765451995523
  lastModifiedBy: h6PQP2LANMyAy0DY
_key: '!folders!Kjpd5UzKteKgjIqB'
